#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CostManagement")]
	public partial class QLGTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertm_Product_Ingredient(m_Product_Ingredient instance);
    partial void Updatem_Product_Ingredient(m_Product_Ingredient instance);
    partial void Deletem_Product_Ingredient(m_Product_Ingredient instance);
    partial void Insertt_User_Activity_Log(t_User_Activity_Log instance);
    partial void Updatet_User_Activity_Log(t_User_Activity_Log instance);
    partial void Deletet_User_Activity_Log(t_User_Activity_Log instance);
    partial void Insertm_Product_Material(m_Product_Material instance);
    partial void Updatem_Product_Material(m_Product_Material instance);
    partial void Deletem_Product_Material(m_Product_Material instance);
    partial void Insertt_Account(t_Account instance);
    partial void Updatet_Account(t_Account instance);
    partial void Deletet_Account(t_Account instance);
    partial void Insertt_Ingredient(t_Ingredient instance);
    partial void Updatet_Ingredient(t_Ingredient instance);
    partial void Deletet_Ingredient(t_Ingredient instance);
    partial void Insertt_Material(t_Material instance);
    partial void Updatet_Material(t_Material instance);
    partial void Deletet_Material(t_Material instance);
    partial void Insertt_Material_Type(t_Material_Type instance);
    partial void Updatet_Material_Type(t_Material_Type instance);
    partial void Deletet_Material_Type(t_Material_Type instance);
    partial void Insertt_Product(t_Product instance);
    partial void Updatet_Product(t_Product instance);
    partial void Deletet_Product(t_Product instance);
    #endregion
		
		public QLGTDataContext() : 
				base(global::DAL.Properties.Settings.Default.CostManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLGTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLGTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLGTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLGTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<m_Product_Ingredient> m_Product_Ingredients
		{
			get
			{
				return this.GetTable<m_Product_Ingredient>();
			}
		}
		
		public System.Data.Linq.Table<t_User_Activity_Log> t_User_Activity_Logs
		{
			get
			{
				return this.GetTable<t_User_Activity_Log>();
			}
		}
		
		public System.Data.Linq.Table<m_Product_Material> m_Product_Materials
		{
			get
			{
				return this.GetTable<m_Product_Material>();
			}
		}
		
		public System.Data.Linq.Table<t_Account> t_Accounts
		{
			get
			{
				return this.GetTable<t_Account>();
			}
		}
		
		public System.Data.Linq.Table<t_Ingredient> t_Ingredients
		{
			get
			{
				return this.GetTable<t_Ingredient>();
			}
		}
		
		public System.Data.Linq.Table<t_Material> t_Materials
		{
			get
			{
				return this.GetTable<t_Material>();
			}
		}
		
		public System.Data.Linq.Table<t_Material_Type> t_Material_Types
		{
			get
			{
				return this.GetTable<t_Material_Type>();
			}
		}
		
		public System.Data.Linq.Table<t_Product> t_Products
		{
			get
			{
				return this.GetTable<t_Product>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.m_Product_Ingredient")]
	public partial class m_Product_Ingredient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ingredient_id;
		
		private string _product_code;
		
		private System.Nullable<int> _quantity;
		
		private System.Nullable<int> _price;
		
		private EntityRef<t_Ingredient> _t_Ingredient;
		
		private EntityRef<t_Product> _t_Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oningredient_idChanging(string value);
    partial void Oningredient_idChanged();
    partial void Onproduct_codeChanging(string value);
    partial void Onproduct_codeChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    #endregion
		
		public m_Product_Ingredient()
		{
			this._t_Ingredient = default(EntityRef<t_Ingredient>);
			this._t_Product = default(EntityRef<t_Product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ingredient_id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ingredient_id
		{
			get
			{
				return this._ingredient_id;
			}
			set
			{
				if ((this._ingredient_id != value))
				{
					if (this._t_Ingredient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oningredient_idChanging(value);
					this.SendPropertyChanging();
					this._ingredient_id = value;
					this.SendPropertyChanged("ingredient_id");
					this.Oningredient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_code", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string product_code
		{
			get
			{
				return this._product_code;
			}
			set
			{
				if ((this._product_code != value))
				{
					if (this._t_Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_codeChanging(value);
					this.SendPropertyChanging();
					this._product_code = value;
					this.SendPropertyChanged("product_code");
					this.Onproduct_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Ingredient_m_Product_Ingredient", Storage="_t_Ingredient", ThisKey="ingredient_id", OtherKey="ingredient_id", IsForeignKey=true)]
		public t_Ingredient t_Ingredient
		{
			get
			{
				return this._t_Ingredient.Entity;
			}
			set
			{
				t_Ingredient previousValue = this._t_Ingredient.Entity;
				if (((previousValue != value) 
							|| (this._t_Ingredient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._t_Ingredient.Entity = null;
						previousValue.m_Product_Ingredients.Remove(this);
					}
					this._t_Ingredient.Entity = value;
					if ((value != null))
					{
						value.m_Product_Ingredients.Add(this);
						this._ingredient_id = value.ingredient_id;
					}
					else
					{
						this._ingredient_id = default(string);
					}
					this.SendPropertyChanged("t_Ingredient");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Product_m_Product_Ingredient", Storage="_t_Product", ThisKey="product_code", OtherKey="product_code", IsForeignKey=true)]
		public t_Product t_Product
		{
			get
			{
				return this._t_Product.Entity;
			}
			set
			{
				t_Product previousValue = this._t_Product.Entity;
				if (((previousValue != value) 
							|| (this._t_Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._t_Product.Entity = null;
						previousValue.m_Product_Ingredients.Remove(this);
					}
					this._t_Product.Entity = value;
					if ((value != null))
					{
						value.m_Product_Ingredients.Add(this);
						this._product_code = value.product_code;
					}
					else
					{
						this._product_code = default(string);
					}
					this.SendPropertyChanged("t_Product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_User_Activity_Log")]
	public partial class t_User_Activity_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _history_log;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhistory_logChanging(string value);
    partial void Onhistory_logChanged();
    #endregion
		
		public t_User_Activity_Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_history_log", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string history_log
		{
			get
			{
				return this._history_log;
			}
			set
			{
				if ((this._history_log != value))
				{
					this.Onhistory_logChanging(value);
					this.SendPropertyChanging();
					this._history_log = value;
					this.SendPropertyChanged("history_log");
					this.Onhistory_logChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.m_Product_Material")]
	public partial class m_Product_Material : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _material_id;
		
		private string _product_code;
		
		private System.Nullable<int> _quantity;
		
		private System.Nullable<int> _price;
		
		private EntityRef<t_Material> _t_Material;
		
		private EntityRef<t_Product> _t_Product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmaterial_idChanging(string value);
    partial void Onmaterial_idChanged();
    partial void Onproduct_codeChanging(string value);
    partial void Onproduct_codeChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    #endregion
		
		public m_Product_Material()
		{
			this._t_Material = default(EntityRef<t_Material>);
			this._t_Product = default(EntityRef<t_Product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material_id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string material_id
		{
			get
			{
				return this._material_id;
			}
			set
			{
				if ((this._material_id != value))
				{
					if (this._t_Material.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmaterial_idChanging(value);
					this.SendPropertyChanging();
					this._material_id = value;
					this.SendPropertyChanged("material_id");
					this.Onmaterial_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_code", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string product_code
		{
			get
			{
				return this._product_code;
			}
			set
			{
				if ((this._product_code != value))
				{
					if (this._t_Product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_codeChanging(value);
					this.SendPropertyChanging();
					this._product_code = value;
					this.SendPropertyChanged("product_code");
					this.Onproduct_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Material_m_Product_Material", Storage="_t_Material", ThisKey="material_id", OtherKey="material_id", IsForeignKey=true)]
		public t_Material t_Material
		{
			get
			{
				return this._t_Material.Entity;
			}
			set
			{
				t_Material previousValue = this._t_Material.Entity;
				if (((previousValue != value) 
							|| (this._t_Material.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._t_Material.Entity = null;
						previousValue.m_Product_Materials.Remove(this);
					}
					this._t_Material.Entity = value;
					if ((value != null))
					{
						value.m_Product_Materials.Add(this);
						this._material_id = value.material_id;
					}
					else
					{
						this._material_id = default(string);
					}
					this.SendPropertyChanged("t_Material");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Product_m_Product_Material", Storage="_t_Product", ThisKey="product_code", OtherKey="product_code", IsForeignKey=true)]
		public t_Product t_Product
		{
			get
			{
				return this._t_Product.Entity;
			}
			set
			{
				t_Product previousValue = this._t_Product.Entity;
				if (((previousValue != value) 
							|| (this._t_Product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._t_Product.Entity = null;
						previousValue.m_Product_Materials.Remove(this);
					}
					this._t_Product.Entity = value;
					if ((value != null))
					{
						value.m_Product_Materials.Add(this);
						this._product_code = value.product_code;
					}
					else
					{
						this._product_code = default(string);
					}
					this.SendPropertyChanged("t_Product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_Account")]
	public partial class t_Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _staff_id;
		
		private string _staff_name;
		
		private string _password;
		
		private string _phone;
		
		private string _role;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstaff_idChanging(string value);
    partial void Onstaff_idChanged();
    partial void Onstaff_nameChanging(string value);
    partial void Onstaff_nameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    #endregion
		
		public t_Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_id", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string staff_id
		{
			get
			{
				return this._staff_id;
			}
			set
			{
				if ((this._staff_id != value))
				{
					this.Onstaff_idChanging(value);
					this.SendPropertyChanging();
					this._staff_id = value;
					this.SendPropertyChanged("staff_id");
					this.Onstaff_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_name", DbType="NVarChar(100)")]
		public string staff_name
		{
			get
			{
				return this._staff_name;
			}
			set
			{
				if ((this._staff_name != value))
				{
					this.Onstaff_nameChanging(value);
					this.SendPropertyChanging();
					this._staff_name = value;
					this.SendPropertyChanged("staff_name");
					this.Onstaff_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(100)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(13)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(10)")]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_Ingredient")]
	public partial class t_Ingredient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ingredient_id;
		
		private string _ingredient_name;
		
		private string _unit;
		
		private System.Nullable<int> _price_per_unit;
		
		private EntitySet<m_Product_Ingredient> _m_Product_Ingredients;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oningredient_idChanging(string value);
    partial void Oningredient_idChanged();
    partial void Oningredient_nameChanging(string value);
    partial void Oningredient_nameChanged();
    partial void OnunitChanging(string value);
    partial void OnunitChanged();
    partial void Onprice_per_unitChanging(System.Nullable<int> value);
    partial void Onprice_per_unitChanged();
    #endregion
		
		public t_Ingredient()
		{
			this._m_Product_Ingredients = new EntitySet<m_Product_Ingredient>(new Action<m_Product_Ingredient>(this.attach_m_Product_Ingredients), new Action<m_Product_Ingredient>(this.detach_m_Product_Ingredients));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ingredient_id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ingredient_id
		{
			get
			{
				return this._ingredient_id;
			}
			set
			{
				if ((this._ingredient_id != value))
				{
					this.Oningredient_idChanging(value);
					this.SendPropertyChanging();
					this._ingredient_id = value;
					this.SendPropertyChanged("ingredient_id");
					this.Oningredient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ingredient_name", DbType="NVarChar(255)")]
		public string ingredient_name
		{
			get
			{
				return this._ingredient_name;
			}
			set
			{
				if ((this._ingredient_name != value))
				{
					this.Oningredient_nameChanging(value);
					this.SendPropertyChanging();
					this._ingredient_name = value;
					this.SendPropertyChanged("ingredient_name");
					this.Oningredient_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit", DbType="VarChar(20)")]
		public string unit
		{
			get
			{
				return this._unit;
			}
			set
			{
				if ((this._unit != value))
				{
					this.OnunitChanging(value);
					this.SendPropertyChanging();
					this._unit = value;
					this.SendPropertyChanged("unit");
					this.OnunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_per_unit", DbType="Int")]
		public System.Nullable<int> price_per_unit
		{
			get
			{
				return this._price_per_unit;
			}
			set
			{
				if ((this._price_per_unit != value))
				{
					this.Onprice_per_unitChanging(value);
					this.SendPropertyChanging();
					this._price_per_unit = value;
					this.SendPropertyChanged("price_per_unit");
					this.Onprice_per_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Ingredient_m_Product_Ingredient", Storage="_m_Product_Ingredients", ThisKey="ingredient_id", OtherKey="ingredient_id")]
		public EntitySet<m_Product_Ingredient> m_Product_Ingredients
		{
			get
			{
				return this._m_Product_Ingredients;
			}
			set
			{
				this._m_Product_Ingredients.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_m_Product_Ingredients(m_Product_Ingredient entity)
		{
			this.SendPropertyChanging();
			entity.t_Ingredient = this;
		}
		
		private void detach_m_Product_Ingredients(m_Product_Ingredient entity)
		{
			this.SendPropertyChanging();
			entity.t_Ingredient = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_Material")]
	public partial class t_Material : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _material_id;
		
		private string _material_name;
		
		private string _unit;
		
		private System.Nullable<int> _price_per_unit;
		
		private string _material_type_id;
		
		private EntitySet<m_Product_Material> _m_Product_Materials;
		
		private EntityRef<t_Material_Type> _t_Material_Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmaterial_idChanging(string value);
    partial void Onmaterial_idChanged();
    partial void Onmaterial_nameChanging(string value);
    partial void Onmaterial_nameChanged();
    partial void OnunitChanging(string value);
    partial void OnunitChanged();
    partial void Onprice_per_unitChanging(System.Nullable<int> value);
    partial void Onprice_per_unitChanged();
    partial void Onmaterial_type_idChanging(string value);
    partial void Onmaterial_type_idChanged();
    #endregion
		
		public t_Material()
		{
			this._m_Product_Materials = new EntitySet<m_Product_Material>(new Action<m_Product_Material>(this.attach_m_Product_Materials), new Action<m_Product_Material>(this.detach_m_Product_Materials));
			this._t_Material_Type = default(EntityRef<t_Material_Type>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material_id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string material_id
		{
			get
			{
				return this._material_id;
			}
			set
			{
				if ((this._material_id != value))
				{
					this.Onmaterial_idChanging(value);
					this.SendPropertyChanging();
					this._material_id = value;
					this.SendPropertyChanged("material_id");
					this.Onmaterial_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material_name", DbType="NVarChar(255)")]
		public string material_name
		{
			get
			{
				return this._material_name;
			}
			set
			{
				if ((this._material_name != value))
				{
					this.Onmaterial_nameChanging(value);
					this.SendPropertyChanging();
					this._material_name = value;
					this.SendPropertyChanged("material_name");
					this.Onmaterial_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit", DbType="VarChar(20)")]
		public string unit
		{
			get
			{
				return this._unit;
			}
			set
			{
				if ((this._unit != value))
				{
					this.OnunitChanging(value);
					this.SendPropertyChanging();
					this._unit = value;
					this.SendPropertyChanged("unit");
					this.OnunitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_per_unit", DbType="Int")]
		public System.Nullable<int> price_per_unit
		{
			get
			{
				return this._price_per_unit;
			}
			set
			{
				if ((this._price_per_unit != value))
				{
					this.Onprice_per_unitChanging(value);
					this.SendPropertyChanging();
					this._price_per_unit = value;
					this.SendPropertyChanged("price_per_unit");
					this.Onprice_per_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material_type_id", DbType="VarChar(20)")]
		public string material_type_id
		{
			get
			{
				return this._material_type_id;
			}
			set
			{
				if ((this._material_type_id != value))
				{
					if (this._t_Material_Type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmaterial_type_idChanging(value);
					this.SendPropertyChanging();
					this._material_type_id = value;
					this.SendPropertyChanged("material_type_id");
					this.Onmaterial_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Material_m_Product_Material", Storage="_m_Product_Materials", ThisKey="material_id", OtherKey="material_id")]
		public EntitySet<m_Product_Material> m_Product_Materials
		{
			get
			{
				return this._m_Product_Materials;
			}
			set
			{
				this._m_Product_Materials.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Material_Type_t_Material", Storage="_t_Material_Type", ThisKey="material_type_id", OtherKey="material_type_id", IsForeignKey=true)]
		public t_Material_Type t_Material_Type
		{
			get
			{
				return this._t_Material_Type.Entity;
			}
			set
			{
				t_Material_Type previousValue = this._t_Material_Type.Entity;
				if (((previousValue != value) 
							|| (this._t_Material_Type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._t_Material_Type.Entity = null;
						previousValue.t_Materials.Remove(this);
					}
					this._t_Material_Type.Entity = value;
					if ((value != null))
					{
						value.t_Materials.Add(this);
						this._material_type_id = value.material_type_id;
					}
					else
					{
						this._material_type_id = default(string);
					}
					this.SendPropertyChanged("t_Material_Type");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_m_Product_Materials(m_Product_Material entity)
		{
			this.SendPropertyChanging();
			entity.t_Material = this;
		}
		
		private void detach_m_Product_Materials(m_Product_Material entity)
		{
			this.SendPropertyChanging();
			entity.t_Material = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_Material_Type")]
	public partial class t_Material_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _material_type_id;
		
		private string _material_type_name;
		
		private EntitySet<t_Material> _t_Materials;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmaterial_type_idChanging(string value);
    partial void Onmaterial_type_idChanged();
    partial void Onmaterial_type_nameChanging(string value);
    partial void Onmaterial_type_nameChanged();
    #endregion
		
		public t_Material_Type()
		{
			this._t_Materials = new EntitySet<t_Material>(new Action<t_Material>(this.attach_t_Materials), new Action<t_Material>(this.detach_t_Materials));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material_type_id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string material_type_id
		{
			get
			{
				return this._material_type_id;
			}
			set
			{
				if ((this._material_type_id != value))
				{
					this.Onmaterial_type_idChanging(value);
					this.SendPropertyChanging();
					this._material_type_id = value;
					this.SendPropertyChanged("material_type_id");
					this.Onmaterial_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material_type_name", DbType="NVarChar(255)")]
		public string material_type_name
		{
			get
			{
				return this._material_type_name;
			}
			set
			{
				if ((this._material_type_name != value))
				{
					this.Onmaterial_type_nameChanging(value);
					this.SendPropertyChanging();
					this._material_type_name = value;
					this.SendPropertyChanged("material_type_name");
					this.Onmaterial_type_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Material_Type_t_Material", Storage="_t_Materials", ThisKey="material_type_id", OtherKey="material_type_id")]
		public EntitySet<t_Material> t_Materials
		{
			get
			{
				return this._t_Materials;
			}
			set
			{
				this._t_Materials.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_t_Materials(t_Material entity)
		{
			this.SendPropertyChanging();
			entity.t_Material_Type = this;
		}
		
		private void detach_t_Materials(t_Material entity)
		{
			this.SendPropertyChanging();
			entity.t_Material_Type = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_Product")]
	public partial class t_Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _product_code;
		
		private string _product_name;
		
		private EntitySet<m_Product_Ingredient> _m_Product_Ingredients;
		
		private EntitySet<m_Product_Material> _m_Product_Materials;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_codeChanging(string value);
    partial void Onproduct_codeChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    #endregion
		
		public t_Product()
		{
			this._m_Product_Ingredients = new EntitySet<m_Product_Ingredient>(new Action<m_Product_Ingredient>(this.attach_m_Product_Ingredients), new Action<m_Product_Ingredient>(this.detach_m_Product_Ingredients));
			this._m_Product_Materials = new EntitySet<m_Product_Material>(new Action<m_Product_Material>(this.attach_m_Product_Materials), new Action<m_Product_Material>(this.detach_m_Product_Materials));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_code", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string product_code
		{
			get
			{
				return this._product_code;
			}
			set
			{
				if ((this._product_code != value))
				{
					this.Onproduct_codeChanging(value);
					this.SendPropertyChanging();
					this._product_code = value;
					this.SendPropertyChanged("product_code");
					this.Onproduct_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(255)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Product_m_Product_Ingredient", Storage="_m_Product_Ingredients", ThisKey="product_code", OtherKey="product_code")]
		public EntitySet<m_Product_Ingredient> m_Product_Ingredients
		{
			get
			{
				return this._m_Product_Ingredients;
			}
			set
			{
				this._m_Product_Ingredients.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="t_Product_m_Product_Material", Storage="_m_Product_Materials", ThisKey="product_code", OtherKey="product_code")]
		public EntitySet<m_Product_Material> m_Product_Materials
		{
			get
			{
				return this._m_Product_Materials;
			}
			set
			{
				this._m_Product_Materials.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_m_Product_Ingredients(m_Product_Ingredient entity)
		{
			this.SendPropertyChanging();
			entity.t_Product = this;
		}
		
		private void detach_m_Product_Ingredients(m_Product_Ingredient entity)
		{
			this.SendPropertyChanging();
			entity.t_Product = null;
		}
		
		private void attach_m_Product_Materials(m_Product_Material entity)
		{
			this.SendPropertyChanging();
			entity.t_Product = this;
		}
		
		private void detach_m_Product_Materials(m_Product_Material entity)
		{
			this.SendPropertyChanging();
			entity.t_Product = null;
		}
	}
}
#pragma warning restore 1591
